# S3 数据处理与分析: Questions

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Q1: 学生成绩计算

In [10]:
marks = pd.read_excel('marks.xlsx', 'Sheet1', dtype={"学号": str})
marks.head(5)

     班级        学号  期中成绩  期末成绩  平时成绩  实验成绩
0  网络01  07020511    89    79    93    87
1  网络01  07020206    66    56    78    84
2  网络01  07020213    88    57    88    84
3  网络01  07020217    81    61    88    87
4  网络01  07020308    81    70    90    83

In [11]:
marks.describe()

            期中成绩       期末成绩       平时成绩       实验成绩
count  65.000000  65.000000  65.000000  65.000000
mean   81.523077  69.400000  88.584615  83.584615
std     9.953184  11.095889   6.580968   5.317695
min    54.000000  45.000000  74.000000  68.000000
25%    74.000000  61.000000  84.000000  80.000000
50%    83.000000  67.000000  90.000000  84.000000
75%    90.000000  78.000000  93.000000  87.000000
max    98.000000  95.000000  98.000000  95.000000